# Generated by Django 5.1.2 on 2024-11-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaivarity_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='chai',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='chaireview',
            old_name='chai',
            new_name='review',
        ),
    ]
